APP_NAME: ${APP_NAME}
---
spring:
  spring:
  profiles: dev
  datasource:
    username: ${DB_USER}
    password: ${DB_PWD}
    url: ${DB_CONN}
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: ${APP_NAME}
