APP_NAME: ${APP_NAME}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
---
spring:
  profiles: dev
  datasource:
    username: ${DB_USER}
    password: ${DB_PWD}
    url: ${DB_CONN}
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: ${APP_NAME}
  flyway:
    locations: classpath:db/migration/mysql
    baselineOnMigrate: true

---
spring:
  profiles: test
  datasource:
    platform: h2
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: ${APP_NAME}
  cache:
    type: none
  flyway:
      locations: classpath:db/migration/h2
      baselineOnMigrate: true